# 1: Numpy Arrays

`numpy`: the foundational library that helps us perform these computations

Numpy's core contribution is a new data-type called an `array`

`Array` is similar to `list`, but there are some restrictions allow numpy to:


1: more efficient in performing mathematical and scientific computations

2: Expose functions that allow numpy to do necessary linear algebra for machine learning and statistics

In [2]:
import numpy as np

## What is an Array?

An array is a multi-dimensional grid of values

Demonstration:

In [3]:
# create an array from a list

x_1d=np.array([1,2,3])
print(x_1d)

[1 2 3]


A 1-dimensional array as a list of numbers

In [4]:
# We can index like we did with lists
print(x_1d[0]) # the first item in x-1d
print(x_1d[0:2]) # first and second we do not include 2

1
[1 2]


Note that the range of indices does not include the end-point that is 

In [5]:
print(x_1d[0:3] == x_1d[:]) # since one two three four,
# we only have 3 items, therefore it is the complete array
print(x_1d[0:2])

[ True  True  True]
[1 2]


Next, a 2-dimensional array (a matrix)

In [6]:
x_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


There are three rows and three columns. How to access the values in this array

Also index from 0, if we want `6`, we would ask for the (1,2) element

In [7]:
print(x_2d[1,2])

6


In [8]:
print(x_2d[0,0])

1


To get the first , and then second rows

In [9]:
print(x_2d[0, :])
print(x_2d[1, :])

[1 2 3]
[4 5 6]


Or the columns

In [10]:
print(x_2d[:, 0])
print(x_2d[:, 1])

[1 4 7]
[2 5 8]


A 3-dimensional array below:

In [11]:
x_3d_list = [[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
x_3d = np.array(x_3d_list)
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


### Array Indexing

Now, there are multiple dimensions, indexing might feel somewhat non-obvious. First the dimensions give two stacked matrices which we can access with

In [12]:
print(x_3d[0])

[[1 2 3]
 [4 5 6]]


In [13]:
print(x_3d[1])

[[10 20 30]
 [40 50 60]]


In the case of the first, it is synonymous with

In [14]:
print(x_3d[0,:,:])

[[1 2 3]
 [4 5 6]]


Let’s work through another example to further clarify this concept with our
3-dimensional array.

Our goal will be to find the index that retrieves the `4` out of `x_3d`.



In [15]:
print(f"The 0 element is {x_3d_list[0]}")
print(f"The 1 element is {x_3d_list[1]}")

The 0 element is [[1, 2, 3], [4, 5, 6]]
The 1 element is [[10, 20, 30], [40, 50, 60]]


In [16]:
print(f"The 0 element of the 0 element is {x_3d_list[0][0]}")
print(f"The 1 element of the 0 element is {x_3d_list[0][1]}")

The 0 element of the 0 element is [1, 2, 3]
The 1 element of the 0 element is [4, 5, 6]


In [17]:
print(f"The 0 element of the 1 element of the 0 element is {x_3d_list[0][1][0]}")

The 0 element of the 1 element of the 0 element is 4


In [18]:
print(x_3d[0, 1, 0])

4


Finally, got it!

Slicing- select multiple elements at a time

In [19]:
print(x_3d[0, 0, :])

[1 2 3]


Notice that we put a `:` on the dimension where we want to select all of the elements. We can also
slice out subsets of the elements by doing `start:stop+1`.

Notice how the following arrays differ.

In [20]:
print(x_3d[:, 0, :])
print(x_3d[:, 0, 0:2])
print(x_3d[:, 0, :2])  # the 0  in 0:2 is optional

[[ 1  2  3]
 [10 20 30]]
[[ 1  2]
 [10 20]]
[[ 1  2]
 [10 20]]


## Array Functionality

### Array Properties


The two most frequently used properties are `shape` and `dtype`.

`shape` tells us how many elements are in each array dimension.

`dtype` tells us the types of an array’s elements.

Let’s do some examples to see these properties in action.

In [21]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print(x.dtype)

(2, 3)
int64


In [22]:
rows, columns = x.shape
print(f"rows = {rows}, columns = {columns}")

rows = 2, columns = 3


In [23]:
x = np.array([True, False, True])
print(x.shape)
print(x.dtype)

(3,)
bool


Note that in the above, the `(3,)` represents a tuple of length 1, distinct from a scalar integer `3`.

In [24]:
x = np.array([
    [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]],
    [[7.0, 8.0], [9.0, 10.0], [11.0, 12.0]]
])
print(x.shape)
print(x.dtype)

(2, 3, 2)
float64


### Creating Arrays

It is impractocal to define arrays by hand. We use default values then fill it with other values. We use `np.zeros` and `np.ones`

In [25]:
sizes = (2, 3, 4)
x = np.zeros(sizes) # note, a tuple!
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
y = np.ones((4))
y

array([1., 1., 1., 1.])

### Broadcasting Operations


Two types of operations

1. Operations between an array and a single number.  
1. Operations between two arrays of the same shape.  


When we perform operations on an array by using a single number, we simply apply that operation to every element of the array.

In [27]:
# Using np.ones to create an array
x = np.ones((2, 2))
print("x = ", x)
print("2 + x = ", 2 + x)
print("2 - x = ", 2 - x)
print("2 * x = ", 2 * x)
print("x / 2 = ", x / 2)

x =  [[1. 1.]
 [1. 1.]]
2 + x =  [[3. 3.]
 [3. 3.]]
2 - x =  [[1. 1.]
 [1. 1.]]
2 * x =  [[2. 2.]
 [2. 2.]]
x / 2 =  [[0.5 0.5]
 [0.5 0.5]]


## Universal Functions

In [28]:
x=np.linspace(0.5,25,10)
# This is similar to range -- but spits out 50 evenly to 25

In [29]:
x

array([ 0.5       ,  3.22222222,  5.94444444,  8.66666667, 11.38888889,
       14.11111111, 16.83333333, 19.55555556, 22.27777778, 25.        ])

In [30]:
# Applies the sin function to each element of x
np.sin(x)

array([ 0.47942554, -0.08054223, -0.33229977,  0.68755122, -0.92364381,
        0.99966057, -0.9024271 ,  0.64879484, -0.28272056, -0.13235175])

Of course, we could do the same thing with a comprehension, but
the code would be both less readable and less efficient.

In [31]:
np.array([np.sin(xval) for xval in x])

array([ 0.47942554, -0.08054223, -0.33229977,  0.68755122, -0.92364381,
        0.99966057, -0.9024271 ,  0.64879484, -0.28272056, -0.13235175])

In [32]:
# Takes log of each element of x
np.log(x)

array([-0.69314718,  1.17007125,  1.78245708,  2.15948425,  2.43263822,
        2.64696251,  2.82336105,  2.97325942,  3.10358967,  3.21887582])

In [33]:
# Calculate log(z) * z elementwise
z = np.array([1,2,3])
np.log(z) * z

array([0.        , 1.38629436, 3.29583687])

## Other Useful Array Operation

In [34]:
x = np.linspace(0, 25, 10)

In [35]:
np.mean(x)

12.5

In [36]:
np.std(x)

7.9785592313028175

In [37]:
# np.min, np.median, etc... are also defined
np.max(x)

25.0

In [38]:
np.diff(x)

array([2.77777778, 2.77777778, 2.77777778, 2.77777778, 2.77777778,
       2.77777778, 2.77777778, 2.77777778, 2.77777778])

In [39]:
np.reshape(x, (5, 2))

array([[ 0.        ,  2.77777778],
       [ 5.55555556,  8.33333333],
       [11.11111111, 13.88888889],
       [16.66666667, 19.44444444],
       [22.22222222, 25.        ]])

In [40]:
print(x.mean())
print(x.std())
print(x.max())
# print(x.diff())  # this one is not a method...
print(x.reshape((5, 2)))

12.5
7.9785592313028175
25.0
[[ 0.          2.77777778]
 [ 5.55555556  8.33333333]
 [11.11111111 13.88888889]
 [16.66666667 19.44444444]
 [22.22222222 25.        ]]


Finally, `np.vectorize` can be conveniently used with numpy broadcasting and any functions.

In [41]:
np.random.seed(42)
x = np.random.rand(10)
print(x)

def f(val):
    if val < 0.3:
        return "low"
    else:
        return "high"

print(f(0.1)) # scalar, no problem
# f(x) # array, fails since f() is scalar
f_vec = np.vectorize(f)
print(f_vec(x))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
low
['high' 'high' 'high' 'high' 'low' 'low' 'low' 'high' 'high' 'high']


## Exercises


<a id='exerciselist-0'></a>
**Exercise 1**

Try indexing into another element of your choice from the
3-dimensional array.

Building an understanding of indexing means working through this
type of operation several times -- without skipping steps!

([*back to text*](#exercise-0))

**Exercise 2**

Look at the 2-dimensional array `x_2d`.

Does the inner-most index correspond to rows or columns? What does the
outer-most index correspond to?

Write your thoughts.

([*back to text*](#exercise-1))

**Exercise 3**

What would you do to extract the array `[[5, 6], [50, 60]]`?

([*back to text*](#exercise-2))

**Exercise 4**

Do you recall what multiplication by an integer did for lists?

How does this differ?

([*back to text*](#exercise-3))

**Exercise 5**

Let's revisit a bond pricing example we saw in Control flow.

Recall that the equation for pricing a bond with coupon payment $ C $,
face value $ M $, yield to maturity $ i $, and periods to maturity
$ N $ is

$$
\begin{align*}
    P &= \left(\sum_{n=1}^N \frac{C}{(i+1)^n}\right) + \frac{M}{(1+i)^N} \\
      &= C \left(\frac{1 - (1+i)^{-N}}{i} \right) + M(1+i)^{-N}
\end{align*}
$$

In the code cell below, we have defined variables for `i`, `M` and `C`.

You have two tasks:

1. Define a numpy array `N` that contains all maturities between 1 and 10 (*hint* look at the `np.arange` function).  
1. Using the equation above, determine the bond prices of all maturity levels in your array.  

**Exercise 1**

In [42]:
print(f"The 0 element is {x_3d_list[0]}")
print(f"The 1 element is {x_3d_list[1]}")

The 0 element is [[1, 2, 3], [4, 5, 6]]
The 1 element is [[10, 20, 30], [40, 50, 60]]


In [14]:
print(f"The 0 element of the 0 element is {x_3d_list[0][0]}")
print(f"The 1 element of the 0 element is {x_3d_list[0][1]}")

The 0 element of the 0 element is [1, 2, 3]
The 1 element of the 0 element is [4, 5, 6]


In [44]:
print(f"The 2 element of the 0 element of the 0 element is {x_3d_list[0][0][1]}")

The 0 element of the 1 element of the 0 element is 2


In [46]:
print(x_3d[0,0,1])

2


**Exercise 2**

**Exercise 3**

In [48]:
print(x_3d[:,1,1:3])

[[ 5  6]
 [50 60]]


**Exercise 4**

It is mutiply all elements by a number if it is array, if it is list, just extend list by orginal elements n times

In [49]:
x=[1,1]

In [50]:
2*x

[1, 1, 1, 1]

In [51]:
x1=np.array([1,1])

In [52]:
2*x1

array([2, 2])

**Exercise 5**